import { useEffect, useState } from 'react';
import { api } from './api';
export default function PlatformPanel() {
  const [source, setSource] = useState('erpnext');
  const [strategy, setStrategy] = useState('react');
  const [task, setTask] = useState('分页读取当前可见记录，核查必要详情，发布有证据引用的只读运营报告。');
  const [run, setRun] = useState<any>(null);
  const [id, setId] = useState('');
  const [history, setHistory] = useState<any[]>([]);
  const [tools, setTools] = useState<any[]>([]);
  const [error, setError] = useState('');
  const [connections, setConnections] = useState<any>(null);
  const [pending, setPending] = useState(false);
  const busy = pending || run?.status === 'running';
  useEffect(() => { let closed = false; api<any[]>('/api/runs').then(v => { if (!closed) setHistory(v); }).catch(e => { if (!closed) setError(e.message); }); api<any[]>(`/api/tools?source=${source}&scenario=${source === 'erpnext' ? 'finance' : 'support'}`).then(v => { if (!closed) setTools(v); }).catch(e => { if (!closed) setError(e.message); }); return () => { closed = true; }; }, [source,id]);
  useEffect(() => { if (!id) return; let closed = false; let timer: ReturnType<typeof setTimeout>; async function poll() { try { const r = await api<any>('/api/runs/' + id); if (!closed) { setRun(r); if (r.status === 'running') timer = setTimeout(poll,700); } } catch(e) { if (!closed) setError((e as Error).message); } } void poll(); return () => { closed = true; clearTimeout(timer); }; }, [id]);
  async function start() { setPending(true); setError(''); try { const r = await api<{id:string}>('/api/runs',{method:'POST',body:JSON.stringify({source,scenario:source === 'erpnext' ? 'finance' : 'support',mode:'live',strategy,task})});setId(r.id);setRun(null); } catch(e) { setError((e as Error).message); } finally { setPending(false); } }
  return <div className="taskbank-workspace"><div className="page-heading"><h1>平台只读工作台</h1></div><p>ERPNext / Zammad 真实 API；平台中的项目初始化记录不是企业生产数据。这里只读与生成报告，不发送消息或修改账务。</p><div className="taskbank-toolbar"><select aria-label="平台" value={source} disabled={busy} onChange={e => setSource(e.target.value)}><option value="erpnext">ERPNext · 财务</option><option value="zammad">Zammad · 客服</option></select><select aria-label="平台运行策略" value={strategy} disabled={busy} onChange={e => setStrategy(e.target.value)}><option value="react">ReAct</option><option value="graph">平台历史读取图</option></select><button className="button secondary" onClick={() => void api('/api/platforms/check',{method:'POST',body:'{}'}).then(setConnections).catch(e => setError(e.message))}>检查连接</button></div><div className="taskbank-detail"><textarea aria-label="平台只读任务" value={task} disabled={busy} onChange={e => setTask(e.target.value)} /><button className="button primary" disabled={busy || !task.trim()} onClick={() => void start()}>运行真实模型</button>{busy && id && <button className="button secondary" onClick={() => void api('/api/runs/'+id+'/cancel',{method:'POST',body:'{}'})}>取消</button>}{error && <p role="alert">{error}</p>}{connections && <pre>{JSON.stringify(connections,null,2)}</pre>}<p>平台读取工具 {tools.length} 个</p><details><summary>工具参数与说明</summary><pre>{JSON.stringify(tools,null,2)}</pre></details><label>平台历史运行<select value={id} onChange={e=>setId(e.target.value)} disabled={busy}><option value="">选择运行</option>{id && !history.some(h=>h.id===id) && <option value={id}>{id}</option>}{history.map(h=><option key={h.id} value={h.id}>{h.request.source} · {h.id.slice(0,8)} · {h.status}</option>)}</select></label>{run && <><p>{run.status} · LLM {run.metrics.modelRequests} · 工具 {run.metrics.toolCalls} · token {run.metrics.inputTokens ?? '未知'} / {run.metrics.outputTokens ?? '未知'}</p><p>{run.evaluation?.note}</p><a href={'/api/runs/'+run.id+'/export/md'}>导出报告</a><details open><summary>报告</summary><pre>{JSON.stringify(run.report || run.finalText || run.error,null,2)}</pre></details><details><summary>真实执行轨迹</summary><pre>{JSON.stringify(run.events,null,2)}</pre></details></>}</div></div>;
}
